version: "3"

services:
  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: liblio
    ports:
    - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
